-- Supabase PostgreSQL Database Schema for ConGrowing
-- Project: wmirdtjpacbdouuixyrg (ap-northeast-2)

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  avatar_url TEXT,
  cri_score INT DEFAULT 750,
  speaking_hours FLOAT DEFAULT 0,
  topic TEXT DEFAULT 'General Conversation',
  is_online BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Calls Table
CREATE TABLE IF NOT EXISTS public.calls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caller_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  receiver_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  duration_seconds INT DEFAULT 0,
  topic TEXT,
  status TEXT DEFAULT 'completed',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create CRI Logs Table
CREATE TABLE IF NOT EXISTS public.cri_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  score_change INT NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS) and Allow Public Read/Insert for Web App
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cri_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update users" ON public.users FOR UPDATE USING (true);

CREATE POLICY "Allow public read calls" ON public.calls FOR SELECT USING (true);
CREATE POLICY "Allow public insert calls" ON public.calls FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read cri_logs" ON public.cri_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert cri_logs" ON public.cri_logs FOR INSERT WITH CHECK (true);

-- 5. Seed Initial Active Speakers
INSERT INTO public.users (username, email, password_hash, name, avatar_url, cri_score, speaking_hours, topic, is_online)
VALUES
  ('elena_r', 'elena@congrowing.com', '1234', 'Elena Rostova', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80', 845, 48.2, 'AI Tech & Future', true),
  ('arjun_m', 'arjun@congrowing.com', '1234', 'Arjun Mehta', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80', 812, 36.8, 'Public Speaking & Debate', true),
  ('sofia_l', 'sofia@congrowing.com', '1234', 'Sofia Loren', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80', 790, 24.1, 'English Fluency & Practice', true),
  ('david_k', 'david@congrowing.com', '1234', 'David Kim', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80', 830, 42.0, 'Startup & Business Pitching', true),
  ('maya_p', 'maya@congrowing.com', '1234', 'Maya Patel', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80', 765, 19.5, 'Job Interview Mock Calls', true),
  ('alex_v', 'alex@congrowing.com', '1234', 'Alex Vance', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80', 880, 58.4, 'Confidence Building', true)
ON CONFLICT (username) DO NOTHING;
